# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=256)),
                ('released_at', models.DateTimeField(help_text=b'When do you want this puzzle to release at?')),
                ('puzzle', s3direct.fields.S3DirectField(unique=True)),
            ],
        ),
    ]
